# Generated by Django 5.0.2 on 2024-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("eid", models.BigIntegerField()),
            ],
            options={
                "db_table": "account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockScreener",
            fields=[
                (
                    "stock_screener_id",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("run_date", models.DateField(blank=True, null=True)),
                ("ticker", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("exp_date", models.DateField(blank=True, null=True)),
                ("upcoming_earnings_date", models.DateField(blank=True, null=True)),
                ("is_earnings_within_2w", models.BooleanField(blank=True, null=True)),
                (
                    "analysts_ratings",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sma_indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rsi_indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "put_l1_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_l1_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l1_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l1_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "put_l2_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_l2_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l2_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l2_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "put_l3_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_l3_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l3_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l3_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "put_l4_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_l4_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l4_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l4_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "put_l5_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_l5_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l5_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "put_l5_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "call_l1_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "call_l1_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l1_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l1_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "call_l2_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "call_l2_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l2_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l2_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "call_l3_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "call_l3_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l3_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l3_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "call_l4_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "call_l4_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l4_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l4_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "call_l5_strikeprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "call_l5_mid_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l5_mid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "call_l5_volume",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("update_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock_screener",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
