# Generated by Django 5.0.2 on 2024-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.UUIDField()),
                ("ticker", models.CharField(blank=True, null=True)),
                ("company_name", models.CharField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("p_e", models.CharField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("change", models.CharField(blank=True, null=True)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("upcoming_earnings", models.DateField(blank=True, null=True)),
                ("etf", models.BooleanField(blank=True, null=True)),
                ("is_options_exists", models.BooleanField(blank=True, null=True)),
                ("round_lot_size", models.IntegerField(blank=True, null=True)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("update_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock_details",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="Employees",
        ),
        migrations.DeleteModel(
            name="HomeProduct",
        ),
    ]
