# Generated by Django 5.0.2 on 2024-02-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_stockdetails_delete_authgroup_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockdetails",
            options={"managed": True},
        ),
    ]
