# Generated by Django 5.0.2 on 2024-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_stockdetails_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockdetails",
            name="id",
        ),
        migrations.AlterField(
            model_name="stockdetails",
            name="stock_id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
