# Generated by Django 5.0.2 on 2024-02-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_stockdetails_id_alter_stockdetails_stock_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockdetails",
            options={"managed": False},
        ),
    ]
